services:
  mc:
    image: ${MC_IMAGE}
    tty: true
    stdin_open: true
    environment:
      EULA: ${EULA}
      VERSION: ${VERSION}
      TYPE: ${TYPE}
      ONLINE_MODE: ${ONLINE_MODE}
      MODE: ${MODE}
      DIFFICULTY: ${DIFFICULTY}
      LEVEL_TYPE: ${LEVEL_TYPE}
      SEED: ${SEED}
      GENERATE_STRUCTURES: ${GENERATE_STRUCTURES}
      SPAWN_NPCS: ${SPAWN_NPCS}
      SPAWN_ANIMALS: ${SPAWN_ANIMALS}
      SPAWN_MONSTERS: ${SPAWN_MONSTERS}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      SIMULATION_DISTANCE: ${SIMULATION_DISTANCE}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK}
      ENABLE_RCON: ${ENABLE_RCON}
    ports:
      - "127.0.0.1:${MC_HOST_PORT}:25565"
    volumes:
      - ${MC_DATA_DIR}:/data
